Id: Zoom.Zoom
Version: 5.0.5
Name: Zoom
Publisher: Zoom
License: Copyright (c) 2020 Zoom Video Communications, Inc. All rights reserved.
LicenseUrl: https://zoom.us/terms
AppMoniker: zoom
Tags: "zoom, admin, webinar, webcam, meeting"
Description: Video and audio conferencing, chat, and webinars
Homepage: https://zoom.us/
Installers:
  - Arch: x86
    Url: https://zoom.us/client/5.0.26213.0602/ZoomInstallerFull.msi
    Sha256: 6D0333BA23C706CD49A1BC816FD636533F4AF41D3583EE79C50AAA157371FE4E
    InstallerType: msi
